### ISSUE TITLE
Launchpad

### ISSUE THREAD

**Issue by oxr463** [aad-for-linux/infrastructure#4]
See: https://launchpad.net/aad-for-linux

**Comment by oxr463** [comment]
@neverrend can you grant me access to these projects:
- https://launchpad.net/pam-aad
- https://launchpad.net/nss-aad
- https://launchpad.net/openvpn-auth-aad

**Comment by oxr463** [comment]
@Ada-Codina can you create an account on launchpad.net so I can add you to the team for the PPA?

**Comment by outzhu** [comment]
outzhu-ac is me.

**Comment by oxr463** [comment]
> outzhu-ac

You've been added.

**Comment by oxr463** [comment]
New PPA: https://launchpad.net/~aad-for-linux/+archive/ubuntu/ppa

New daily builds:
- https://code.launchpad.net/~lramage/+recipe/pam-aad-daily
- https://code.launchpad.net/~aad-for-linux/+recipe/libnss-aad-daily
- https://code.launchpad.net/~aad-for-linux/+recipe/openvpn-auth-aad-daily
